server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango
    username: root
    password: 123456

mybatis:
  type-aliases-package: work.huangxin.mango.model
  mapper-locations: classpath:mappers/*.xml
  #??mapper??
  mapper:
    #???????
    mappers: com.caomei.basemapper
    identity: MYSQL

#swagger??
swagger:
  # ????
  enable: true
  base:
    # ??????????????
    package: com.javafeng
  contact:
    email: blog@javafeng.com
    name: JAVAFENG
    url: https://www.javafeng.com
  description:
  title: ${spring.spring.name} API Document
  url: https://www.javafeng.com
  version: @project.version@